"""创建 Company Trust、Media Library 与 Public Downloads。"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision = "20260904_0008"
down_revision = "20260904_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _ts() -> tuple[sa.Column, sa.Column]:
    """统一时间字段。"""
    return (sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), comment="创建时间"), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), comment="更新时间"))


def _status(name: str) -> sa.CheckConstraint:
    """Trust 状态约束。"""
    return sa.CheckConstraint("status IN ('enabled','disabled','retired')", name=f"{name}_status_value")


def upgrade() -> None:
    """创建 Trust、媒体和下载表。"""
    op.create_table("company_profiles", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("status", sa.String(16), nullable=False, server_default="enabled", comment="状态"), sa.Column("founded_year", sa.Integer(), nullable=True, comment="成立年份"), sa.Column("years_experience", sa.Integer(), nullable=True, comment="从业年限"), sa.Column("employee_count_range", sa.String(80), nullable=True, comment="员工数量范围"), sa.Column("factory_area_sqm", sa.Float(), nullable=True, comment="厂房面积平方米"), sa.Column("annual_capacity_text", sa.Text(), nullable=True, comment="年产能描述"), sa.Column("export_markets_json", sa.JSON(), nullable=True, comment="出口市场JSON数组"), sa.Column("public_phone", sa.String(80), nullable=True, comment="公开电话"), sa.Column("public_email", sa.String(320), nullable=True, comment="公开邮箱"), sa.Column("public_address", sa.Text(), nullable=True, comment="公开地址"), sa.Column("latitude", sa.Float(), nullable=True, comment="公开纬度"), sa.Column("longitude", sa.Float(), nullable=True, comment="公开经度"), sa.Column("logo_media_id", sa.Uuid(), nullable=True, comment="公司Logo媒体ID"), sa.Column("primary_factory_media_id", sa.Uuid(), nullable=True, comment="主工厂媒体ID"), *_ts(), _status("company_profile"), comment="公司公开档案表")
    op.create_table("company_profile_translations", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("company_profile_id", sa.Uuid(), sa.ForeignKey("company_profiles.id", ondelete="CASCADE"), nullable=False, comment="公司档案ID"), sa.Column("locale_id", sa.Uuid(), sa.ForeignKey("locales.id", ondelete="RESTRICT"), nullable=False, comment="语言ID"), sa.Column("company_name", sa.String(240), nullable=False, comment="公司名称"), sa.Column("short_intro", sa.Text(), nullable=False, comment="公司简短介绍"), sa.Column("full_intro", sa.Text(), nullable=False, comment="公司完整介绍"), sa.Column("mission", sa.Text(), nullable=True, comment="使命"), sa.Column("advantages_json", sa.JSON(), nullable=True, comment="公司优势JSON数组"), *_ts(), sa.UniqueConstraint("company_profile_id", "locale_id", name="uq_company_profile_translation_locale"), comment="公司档案翻译表")
    op.create_table("manufacturing_capabilities", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("slug", sa.String(160), unique=True, nullable=False, comment="稳定能力Slug"), sa.Column("capability_type", sa.String(64), nullable=False, comment="能力类型"), sa.Column("status", sa.String(16), nullable=False, server_default="enabled", comment="状态"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("primary_media_id", sa.Uuid(), nullable=True, comment="主媒体ID"), *_ts(), _status("manufacturing_capability"), comment="制造能力表")
    op.create_table("manufacturing_capability_translations", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("capability_id", sa.Uuid(), sa.ForeignKey("manufacturing_capabilities.id", ondelete="CASCADE"), nullable=False, comment="能力ID"), sa.Column("locale_id", sa.Uuid(), sa.ForeignKey("locales.id", ondelete="RESTRICT"), nullable=False, comment="语言ID"), sa.Column("name", sa.String(240), nullable=False, comment="能力名称"), sa.Column("summary", sa.Text(), nullable=True, comment="能力摘要"), sa.Column("description", sa.Text(), nullable=True, comment="能力描述"), sa.Column("key_facts_json", sa.JSON(), nullable=True, comment="关键事实JSON数组"), *_ts(), sa.UniqueConstraint("capability_id", "locale_id", name="uq_capability_translation_locale"), comment="制造能力翻译表")
    op.create_table("equipment", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("slug", sa.String(160), unique=True, nullable=False, comment="稳定设备Slug"), sa.Column("equipment_type", sa.String(80), nullable=False, comment="设备类型"), sa.Column("manufacturer", sa.String(200), nullable=True, comment="制造商"), sa.Column("model", sa.String(160), nullable=True, comment="设备型号"), sa.Column("quantity", sa.Integer(), nullable=True, comment="设备数量"), sa.Column("commissioning_year", sa.Integer(), nullable=True, comment="投产年份"), sa.Column("precision_text", sa.Text(), nullable=True, comment="精度描述"), sa.Column("capacity_text", sa.Text(), nullable=True, comment="能力描述"), sa.Column("status", sa.String(16), nullable=False, server_default="enabled", comment="状态"), sa.Column("featured", sa.Boolean(), nullable=False, server_default=sa.false(), comment="是否推荐"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("primary_media_id", sa.Uuid(), nullable=True, comment="主媒体ID"), *_ts(), _status("equipment"), comment="设备表")
    op.create_table("equipment_translations", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("equipment_id", sa.Uuid(), sa.ForeignKey("equipment.id", ondelete="CASCADE"), nullable=False, comment="设备ID"), sa.Column("locale_id", sa.Uuid(), sa.ForeignKey("locales.id", ondelete="RESTRICT"), nullable=False, comment="语言ID"), sa.Column("name", sa.String(240), nullable=False, comment="设备名称"), sa.Column("summary", sa.Text(), nullable=True, comment="设备摘要"), sa.Column("description", sa.Text(), nullable=True, comment="设备描述"), sa.Column("public_specs_json", sa.JSON(), nullable=True, comment="公开规格JSON"), *_ts(), sa.UniqueConstraint("equipment_id", "locale_id", name="uq_equipment_translation_locale"), comment="设备翻译表")
    simple = {
        "certificates": [("certificate_type", sa.String(80), False), ("certificate_number", sa.String(160), True), ("issuer", sa.String(240), False), ("issue_date", sa.Date(), True), ("expiry_date", sa.Date(), True), ("verification_url", sa.String(800), True), ("public_file_media_id", sa.Uuid(), True)],
        "patents": [("patent_number", sa.String(160), False), ("patent_type", sa.String(80), False), ("application_number", sa.String(160), True), ("filing_date", sa.Date(), True), ("grant_date", sa.Date(), True), ("jurisdiction", sa.String(80), True), ("inventor_text", sa.Text(), True), ("verification_url", sa.String(800), True), ("public_file_media_id", sa.Uuid(), True)],
        "honors": [("issuing_organization", sa.String(240), False), ("award_date", sa.Date(), True)],
        "exhibitions": [("event_name", sa.String(240), False), ("country_code", sa.String(2), True), ("city", sa.String(120), True), ("start_date", sa.Date(), True), ("end_date", sa.Date(), True), ("booth_no", sa.String(80), True)],
    }
    for table, columns in simple.items():
        op.create_table(table, sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("slug", sa.String(160), unique=True, nullable=False, comment="稳定Slug"), *[sa.Column(name, typ, nullable=nullable, comment=name) for name, typ, nullable in columns], sa.Column("status", sa.String(16), nullable=False, server_default="enabled", comment="状态"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("primary_media_id", sa.Uuid(), nullable=True, comment="主媒体ID"), *_ts(), _status(table.rstrip("s")), comment=f"{table} 表")
    for table, parent, parent_table, fields in (("certificate_translations", "certificate_id", "certificates", [("name", sa.String(240), False), ("summary", sa.Text(), True), ("scope", sa.Text(), True)]), ("patent_translations", "patent_id", "patents", [("title", sa.String(240), False), ("summary", sa.Text(), True), ("technical_scope", sa.Text(), True)]), ("honor_translations", "honor_id", "honors", [("title", sa.String(240), False), ("summary", sa.Text(), True)]), ("exhibition_translations", "exhibition_id", "exhibitions", [("title", sa.String(240), False), ("summary", sa.Text(), True), ("description", sa.Text(), True)])):
        op.create_table(table, sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column(parent, sa.Uuid(), sa.ForeignKey(f"{parent_table}.id", ondelete="CASCADE"), nullable=False, comment="主实体ID"), sa.Column("locale_id", sa.Uuid(), sa.ForeignKey("locales.id", ondelete="RESTRICT"), nullable=False, comment="语言ID"), *[sa.Column(name, typ, nullable=nullable, comment=name) for name, typ, nullable in fields], *_ts(), sa.UniqueConstraint(parent, "locale_id", name=f"uq_{table}_locale"), comment=f"{table} 表")
    op.create_table("capability_equipment", sa.Column("capability_id", sa.Uuid(), sa.ForeignKey("manufacturing_capabilities.id", ondelete="CASCADE"), primary_key=True, comment="能力ID"), sa.Column("equipment_id", sa.Uuid(), sa.ForeignKey("equipment.id", ondelete="CASCADE"), primary_key=True, comment="设备ID"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("notes", sa.Text(), nullable=True, comment="关系备注"))
    op.create_table("capability_certificates", sa.Column("capability_id", sa.Uuid(), sa.ForeignKey("manufacturing_capabilities.id", ondelete="CASCADE"), primary_key=True, comment="能力ID"), sa.Column("certificate_id", sa.Uuid(), sa.ForeignKey("certificates.id", ondelete="CASCADE"), primary_key=True, comment="证书ID"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("notes", sa.Text(), nullable=True, comment="关系备注"))
    op.create_table("capability_patents", sa.Column("capability_id", sa.Uuid(), sa.ForeignKey("manufacturing_capabilities.id", ondelete="CASCADE"), primary_key=True, comment="能力ID"), sa.Column("patent_id", sa.Uuid(), sa.ForeignKey("patents.id", ondelete="CASCADE"), primary_key=True, comment="专利ID"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("notes", sa.Text(), nullable=True, comment="关系备注"))
    op.create_table("technology_equipment", sa.Column("technology_id", sa.Uuid(), sa.ForeignKey("technologies.id", ondelete="CASCADE"), primary_key=True, comment="技术ID"), sa.Column("equipment_id", sa.Uuid(), sa.ForeignKey("equipment.id", ondelete="CASCADE"), primary_key=True, comment="设备ID"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), sa.Column("notes", sa.Text(), nullable=True, comment="关系备注"))
    op.create_table("media_assets", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("visibility", sa.String(16), nullable=False, comment="可见性"), sa.Column("media_type", sa.String(16), nullable=False, comment="媒体类型"), sa.Column("storage_bucket", sa.String(120), nullable=False, comment="对象存储桶"), sa.Column("storage_key", sa.String(1000), nullable=False, comment="对象存储键"), sa.Column("original_filename", sa.String(500), nullable=False, comment="原始文件名"), sa.Column("sanitized_filename", sa.String(500), nullable=False, comment="清洗后文件名"), sa.Column("mime_type", sa.String(160), nullable=False, comment="MIME"), sa.Column("file_extension", sa.String(16), nullable=False, comment="扩展名"), sa.Column("file_size_bytes", sa.BigInteger(), nullable=False, comment="文件大小"), sa.Column("sha256", sa.String(64), nullable=False, comment="SHA256"), sa.Column("width", sa.Integer(), nullable=True, comment="宽度"), sa.Column("height", sa.Integer(), nullable=True, comment="高度"), sa.Column("duration_seconds", sa.Float(), nullable=True, comment="视频时长"), sa.Column("checksum_verified", sa.Boolean(), nullable=False, server_default=sa.false(), comment="SHA校验"), sa.Column("malware_scan_status", sa.String(16), nullable=False, server_default="pending", comment="恶意软件扫描状态"), sa.Column("upload_status", sa.String(16), nullable=False, server_default="pending", comment="上传状态"), sa.Column("uploaded_by", sa.Uuid(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True, comment="上传用户"), *_ts(), sa.UniqueConstraint("storage_bucket", "storage_key", name="uq_media_asset_storage_key"), sa.CheckConstraint("visibility IN ('public','private')", name="media_asset_visibility_value"), sa.CheckConstraint("media_type IN ('image','video','document','cad','other')", name="media_asset_media_type_value"), sa.CheckConstraint("malware_scan_status IN ('pending','clean','infected','failed','not_required')", name="media_asset_scan_value"), sa.CheckConstraint("upload_status IN ('pending','ready','rejected','quarantined')", name="media_asset_upload_status_value"), sa.CheckConstraint("(visibility = 'public' AND storage_bucket = 'public-media') OR (visibility = 'private' AND storage_bucket = 'private-rfq')", name="media_asset_bucket_visibility_match"), comment="统一媒体资产表")
    op.create_table("media_asset_translations", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("media_asset_id", sa.Uuid(), sa.ForeignKey("media_assets.id", ondelete="CASCADE"), nullable=False, comment="媒体ID"), sa.Column("locale_id", sa.Uuid(), sa.ForeignKey("locales.id", ondelete="RESTRICT"), nullable=False, comment="语言ID"), sa.Column("alt_text", sa.String(500), nullable=True, comment="Alt文本"), sa.Column("title", sa.String(320), nullable=True, comment="媒体标题"), sa.Column("caption", sa.Text(), nullable=True, comment="媒体说明"), *_ts(), sa.UniqueConstraint("media_asset_id", "locale_id", name="uq_media_asset_translation_locale"), comment="媒体翻译表")
    op.create_table("download_resources", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("slug", sa.String(180), unique=True, nullable=False, comment="下载Slug"), sa.Column("resource_type", sa.String(64), nullable=False, comment="资源类型"), sa.Column("status", sa.String(16), nullable=False, server_default="enabled", comment="状态"), sa.Column("media_asset_id", sa.Uuid(), sa.ForeignKey("media_assets.id", ondelete="RESTRICT"), nullable=False, comment="公开媒体ID"), sa.Column("version_label", sa.String(80), nullable=True, comment="版本标签"), sa.Column("published_date", sa.String(32), nullable=True, comment="发布日期"), sa.Column("requires_form", sa.Boolean(), nullable=False, server_default=sa.false(), comment="是否需要表单"), sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0", comment="排序"), *_ts(), _status("download_resource"), comment="公开下载资源表")
    op.create_table("download_resource_translations", sa.Column("id", sa.Uuid(), primary_key=True, comment="主键ID"), sa.Column("download_resource_id", sa.Uuid(), sa.ForeignKey("download_resources.id", ondelete="CASCADE"), nullable=False, comment="下载资源ID"), sa.Column("locale_id", sa.Uuid(), sa.ForeignKey("locales.id", ondelete="RESTRICT"), nullable=False, comment="语言ID"), sa.Column("title", sa.String(320), nullable=False, comment="下载标题"), sa.Column("summary", sa.Text(), nullable=True, comment="下载摘要"), *_ts(), sa.UniqueConstraint("download_resource_id", "locale_id", name="uq_download_resource_translation_locale"), comment="下载资源翻译表")


def downgrade() -> None:
    """按外键依赖逆序删除 0008 表。"""
    for table in ("download_resource_translations", "download_resources", "media_asset_translations", "media_assets", "technology_equipment", "capability_patents", "capability_certificates", "capability_equipment", "exhibition_translations", "honor_translations", "patent_translations", "certificate_translations", "exhibitions", "honors", "patents", "certificates", "equipment_translations", "equipment", "manufacturing_capability_translations", "manufacturing_capabilities", "company_profile_translations", "company_profiles"):
        op.drop_table(table)

